version: '3.8'

x-node: &node
  build: ./node
  privileged: true
  command: /usr/sbin/sshd -D
  tty: true

services:
  ansible:
    build: ansible
    command: tail -f /dev/null
    volumes:
      - ./ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ./ansible/hosts.yml:/etc/ansible/hosts
      - ./ansible/playbook:/workspace/playbook
      - ./ansible/roles:/workspace/roles
      - ./ansible/etc:/workspace/etc
  node1:
    <<: *node
    ports:
      - 2222:22
  node2:
    <<: *node
    ports:
      - 2223:22
