version: '3.8'

services:
  ansible:
    build: ansible
    command: tail -f /dev/null
    volumes:
      - ./ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ./ansible/hosts:/etc/ansible/hosts
      - ./ansible/playbook:/workspace/playbook
  node:
    privileged: true
    build: ./node
    command: /usr/sbin/sshd -D
    ports:
      - 2222:22
      - 8000:80
      - 13306:3306
