---
- name: Install MySQL server
  hosts: all
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
