---
- name: Copy nginx.conf
  copy:
    src: ../../etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
